spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/weatherfail
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC